/**
 * generate-icons.ts — build the offline house icon set.
 *
 * MLZ Design ships a *curated* icon language so every project draws from the same
 * well and nothing drifts. This script extracts the chosen Lucide glyphs from
 * `@iconify-json/lucide` and freezes them into `src/icons/generated.ts` as inline
 * IconifyIcon data — no runtime network, fully offline, tree-shaken by name.
 *
 * To add an icon: append its Lucide name to CURATED below and run `bun gen:icons`.
 * (Names must exist in the Lucide set — the script fails loudly if one doesn't.)
 *
 *   bun run gen:icons
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { getIconData } from "@iconify/utils";
import lucide from "@iconify-json/lucide/icons.json";

/**
 * The MLZ house icon set — Lucide names, grouped for legibility. Keep it curated:
 * a small, consistent vocabulary beats a kitchen sink. Consumers that need a
 * one-off glyph can register their own via `addCollection` (re-exported).
 */
const CURATED = [
  // Navigation & chevrons
  "chevron-down",
  "chevron-up",
  "chevron-left",
  "chevron-right",
  "chevrons-up-down",
  "arrow-right",
  "arrow-left",
  "arrow-up",
  "arrow-down",
  "arrow-up-right",
  "external-link",
  "menu",
  "ellipsis",
  "ellipsis-vertical",
  // Actions
  "check",
  "check-check",
  "x",
  "plus",
  "minus",
  "search",
  "filter",
  "settings",
  "pencil",
  "trash-2",
  "copy",
  "clipboard",
  "download",
  "upload",
  "share-2",
  "refresh-cw",
  "rotate-cw",
  "log-out",
  "log-in",
  "send",
  "save",
  // Status & signals
  "info",
  "triangle-alert",
  "circle-alert",
  "circle-check",
  "circle-x",
  "circle-help",
  "loader-circle",
  "circle",
  "dot",
  // Objects
  "user",
  "users",
  "house",
  "file",
  "file-text",
  "folder",
  "calendar",
  "clock",
  "mail",
  "bell",
  "star",
  "heart",
  "bookmark",
  "eye",
  "eye-off",
  "lock",
  "lock-open",
  "sun",
  "moon",
  // Developer & media
  "github",
  "code",
  "code-xml",
  "terminal",
  "link",
  "image",
  "play",
  "pause",
  "zap",
  "sparkles",
  "command",
  "panel-left",
  "layout-grid",
] as const;

const iconSet = lucide as Parameters<typeof getIconData>[0];

// Only the render-relevant fields of IconifyIcon — `getIconData` can also emit
// bookkeeping props (e.g. `hidden`) that aren't part of the public type.
const ICON_KEYS = ["body", "left", "top", "width", "height", "rotate", "hFlip", "vFlip"] as const;

const entries = [...CURATED].sort().map((name) => {
  const data = getIconData(iconSet, name);
  if (!data) {
    throw new Error(
      `Lucide icon "${name}" not found. Check the name at https://icones.js.org/collection/lucide`,
    );
  }
  const clean: Record<string, unknown> = {};
  for (const key of ICON_KEYS) {
    if (data[key] !== undefined) clean[key] = data[key];
  }
  return [name, clean] as const;
});

const body = entries
  .map(([name, data]) => `  ${JSON.stringify(name)}: ${JSON.stringify(data)},`)
  .join("\n");

const out = `// AUTO-GENERATED by scripts/generate-icons.ts — do not edit by hand.
// Run \`bun run gen:icons\` to regenerate. Source: @iconify-json/lucide.
import type { IconifyIcon } from "@iconify/react/offline";

/**
 * The MLZ Design house icon set — inline Lucide data, offline and deterministic.
 * Prefer the typed \`<Icon name="…" />\` component over reading this directly.
 */
export const houseIcons = {
${body}
} satisfies Record<string, IconifyIcon>;

/** Union of every curated house icon name. */
export type IconName = keyof typeof houseIcons;

/** Sorted list of every house icon name (handy for galleries / stories). */
export const iconNames = Object.keys(houseIcons) as IconName[];
`;

const target = fileURLToPath(new URL("../src/icons/generated.ts", import.meta.url));
writeFileSync(target, out);
console.log(`✓ Wrote ${entries.length} icons → src/icons/generated.ts`);
