// MLZ Design — colour tokens
// GENERATED by scripts/generate-swift-tokens.ts. Do not edit by hand.
// Source of truth: src/tokens.ts + src/styles/theme.css. Run `bun run gen:swift`.

import SwiftUI
#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

/// The MLZ palette. Brand primitives are fixed; semantic roles adapt to
/// light/dark automatically. Swap the whole accent with ``MLZColor/accent(_:)``.
public enum MLZColor {

    // MARK: Brand primitives (theme-independent)
    public static let paper = Color(srgb: 0xECEBE4)
    public static let paper2 = Color(srgb: 0xE4E2DA)
    public static let paper3 = Color(srgb: 0xDCDAD1)
    public static let ink = Color(srgb: 0x1A1A18)
    public static let ink2 = Color(srgb: 0x4A4A45)
    public static let line = Color(srgb: 0xCBC9BE)
    public static let dangerRed = Color(srgb: 0xED3151)

    // MARK: Semantic roles (light / dark adaptive)
    public static let background = dynamic(light: 0xECEBE4, dark: 0x161614)
    public static let foreground = dynamic(light: 0x1A1A18, dark: 0xE9E8E3)
    public static let card = dynamic(light: 0xECEBE4, dark: 0x1D1D1B)
    public static let cardForeground = dynamic(light: 0x1A1A18, dark: 0xE9E8E3)
    public static let popover = dynamic(light: 0xECEBE4, dark: 0x1D1D1B)
    public static let popoverForeground = dynamic(light: 0x1A1A18, dark: 0xE9E8E3)
    public static let primary = dynamic(light: 0x1A1A18, dark: 0xE9E8E3)
    public static let primaryForeground = dynamic(light: 0xECEBE4, dark: 0x161614)
    public static let secondary = dynamic(light: 0xE4E2DA, dark: 0x262724)
    public static let secondaryForeground = dynamic(light: 0x4A4A45, dark: 0xD2D1CD)
    public static let muted = dynamic(light: 0xE4E2DA, dark: 0x262724)
    public static let mutedForeground = dynamic(light: 0x63615A, dark: 0x9F9F99)
    public static let accent = dynamic(light: 0x00C4C4, dark: 0x00C4C4)
    public static let accentDeep = dynamic(light: 0x007980, dark: 0x00A8AB)
    public static let accentForeground = dynamic(light: 0x1A1A18, dark: 0x161614)
    public static let brandPeriod = dynamic(light: 0x007980, dark: 0x00C4C4)
    public static let border = dynamic(light: 0xCBC9BE, dark: 0x30302E)
    public static let input = dynamic(light: 0xCBC9BE, dark: 0x30302E)
    public static let ring = dynamic(light: 0x00C4C4, dark: 0x00C4C4)
    public static let destructive = dynamic(light: 0xED3151, dark: 0xF8495A)
    public static let destructiveForeground = dynamic(light: 0xECEBE4, dark: 0xF2F2EF)
    public static let success = dynamic(light: 0x3B9555, dark: 0x58B575)
    public static let successForeground = dynamic(light: 0xECEBE4, dark: 0x0B140D)
    public static let warning = dynamic(light: 0xF2B036, dark: 0xFABB41)
    public static let warningForeground = dynamic(light: 0x1A1A18, dark: 0x1B150B)
    public static let info = dynamic(light: 0x2F8ADC, dark: 0x4C9DEB)
    public static let infoForeground = dynamic(light: 0xECEBE4, dark: 0x0B121A)

    // MARK: Accent families
    public enum Accent: String, CaseIterable, Sendable {
        case cyan, blue, green, rust, ink
    }

    /// The (base, deep, foreground) triple for an accent family.
    public static func palette(_ accent: Accent) -> (base: Color, deep: Color, foreground: Color) {
        let hexes = hex(accent)
        return (Color(srgb: hexes.base), Color(srgb: hexes.deep), Color(srgb: hexes.foreground))
    }

    /// The base colour of an accent family (its ``palette(_:)`` .base).
    public static func accent(_ accent: Accent) -> Color { palette(accent).base }

    private static func hex(_ accent: Accent) -> (base: UInt32, deep: UInt32, foreground: UInt32) {
        switch accent {
        case .cyan: return (base: 0x00C4C4, deep: 0x007980, foreground: 0x1A1A18)
        case .blue: return (base: 0x2F8ADC, deep: 0x1B589E, foreground: 0xECEBE4)
        case .green: return (base: 0x51B67A, deep: 0x077045, foreground: 0x1A1A18)
        case .rust: return (base: 0xDB703B, deep: 0x973E16, foreground: 0xECEBE4)
        case .ink: return (base: 0x2B343D, deep: 0x1A2026, foreground: 0xECEBE4)
        }
    }
}

// MARK: - sRGB / dynamic helpers

extension Color {
    /// Build a colour from a packed 0xRRGGBB sRGB value.
    public init(srgb hex: UInt32) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: 1
        )
    }
}

extension MLZColor {
    /// A colour that resolves to `light` or `dark` from the active appearance.
    static func dynamic(light: UInt32, dark: UInt32) -> Color {
        #if canImport(UIKit)
        return Color(UIColor { $0.userInterfaceStyle == .dark ? uiColor(dark) : uiColor(light) })
        #elseif canImport(AppKit)
        return Color(NSColor(name: nil) {
            $0.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua ? nsColor(dark) : nsColor(light)
        })
        #else
        return Color(srgb: light)
        #endif
    }

    #if canImport(UIKit)
    private static func uiColor(_ hex: UInt32) -> UIColor {
        UIColor(
            red: CGFloat((hex >> 16) & 0xFF) / 255,
            green: CGFloat((hex >> 8) & 0xFF) / 255,
            blue: CGFloat(hex & 0xFF) / 255,
            alpha: 1
        )
    }
    #elseif canImport(AppKit)
    private static func nsColor(_ hex: UInt32) -> NSColor {
        NSColor(
            srgbRed: CGFloat((hex >> 16) & 0xFF) / 255,
            green: CGFloat((hex >> 8) & 0xFF) / 255,
            blue: CGFloat(hex & 0xFF) / 255,
            alpha: 1
        )
    }
    #endif
}
