// MLZ Design — motion tokens
// GENERATED by scripts/generate-swift-tokens.ts. Do not edit by hand.
// Source of truth: src/tokens.ts + src/styles/theme.css. Run `bun run gen:swift`.

import SwiftUI

/// The signature easing + durations, as ready-made `Animation`s. `easeOut` is the
/// house curve (entrances, hovers); `easeInOut` is the symmetric loop curve.
public enum MLZMotion {
    public static let durationFast: Double = 0.15
    public static let durationBase: Double = 0.3
    public static let durationSlow: Double = 0.9

    public static func easeOut(_ duration: Double = durationBase) -> Animation {
        .timingCurve(0.22, 0.61, 0.36, 1, duration: duration)
    }
    public static func easeInOut(_ duration: Double = durationBase) -> Animation {
        .timingCurve(0.65, 0, 0.35, 1, duration: duration)
    }

    /// The default entrance/hover animation.
    public static let standard = easeOut()
}
