// MLZ Design — radius scale
// GENERATED by scripts/generate-swift-tokens.ts. Do not edit by hand.
// Source of truth: src/tokens.ts + src/styles/theme.css. Run `bun run gen:swift`.

import CoreGraphics

/// Corner radii — the brand leans sharp/technical, so corners stay tight. Mirrors
/// the CSS `--radius-*` scale (base 4pt).
public enum MLZRadius {
    public static let sm: CGFloat = 2
    public static let md: CGFloat = 4
    public static let lg: CGFloat = 6
    public static let xl: CGFloat = 10
}
