// MLZ Design — spacing scale
// GENERATED by scripts/generate-swift-tokens.ts. Do not edit by hand.
// Source of truth: src/tokens.ts + src/styles/theme.css. Run `bun run gen:swift`.

import CoreGraphics

/// A 4pt spacing grid — the native mirror of the web gap scale. Use these for
/// padding, stack spacing and insets so rhythm matches across platforms.
public enum MLZSpacing {
    public static let grid: CGFloat = 4

    public static let xxs: CGFloat = 2
    public static let xs:  CGFloat = 4
    public static let sm:  CGFloat = 8
    public static let md:  CGFloat = 12
    public static let base: CGFloat = 16
    public static let lg:  CGFloat = 24
    public static let xl:  CGFloat = 32
    public static let xxl: CGFloat = 48
    public static let huge: CGFloat = 64

    /// Arbitrary multiple of the 4pt grid: `MLZSpacing.step(5)` → 20.
    public static func step(_ n: CGFloat) -> CGFloat { grid * n }
}
