// MLZ Design — type tokens
// GENERATED by scripts/generate-swift-tokens.ts. Do not edit by hand.
// Source of truth: src/tokens.ts + src/styles/theme.css. Run `bun run gen:swift`.

import SwiftUI

/// The MLZ type families. These are the font *family* names — register the fonts
/// in your app (bundle the .ttf + list them under `UIAppFonts`, or use a package
/// resource) and these helpers resolve them. Robust: `Font.custom` falls back to
/// the system face if a family is missing, so nothing renders blank.
public enum MLZFont {
    public static let hand    = "Architects Daughter"
    public static let mono    = "Space Mono"
    public static let grotesk = "Space Grotesk"
    public static let serif   = "Instrument Serif"

    /// Hand-drawn display face (headlines, the wordmark feel).
    public static func hand(_ size: CGFloat, relativeTo style: Font.TextStyle = .largeTitle) -> Font {
        .custom(hand, size: size, relativeTo: style)
    }
    /// Monospace — the technical body/label face (the system default voice).
    public static func mono(_ size: CGFloat, relativeTo style: Font.TextStyle = .body) -> Font {
        .custom(mono, size: size, relativeTo: style)
    }
    /// Grotesk — clean headlines (social cards, marketing).
    public static func grotesk(_ size: CGFloat, relativeTo style: Font.TextStyle = .title) -> Font {
        .custom(grotesk, size: size, relativeTo: style)
    }
    /// Editorial serif.
    public static func serif(_ size: CGFloat, relativeTo style: Font.TextStyle = .title) -> Font {
        .custom(serif, size: size, relativeTo: style)
    }
}
